export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN";
export const ADD_DATASETTYPE = "ADD_DATASETTYPE";
export const SET_PROJECT_SELECT = "SET_PROJECT_SELECT";
export const SET_PROJECT = "SET_PROJECT";
export const SET_ERRORS_INITIAL_STATE = "SET_ERRORS_INITIAL_STATE";
